FROM python:3.9-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app/

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y dist-upgrade

RUN apt-get -y install curl ca-certificates gnupg \
    && curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

RUN apt-get update

RUN apt-get -y install postgresql-client-12
RUN apt-get -y install postgresql-client-13
RUN apt-get -y install postgresql-client-14
RUN apt-get -y install postgresql-client-15
RUN apt-get -y install postgresql-client-16
RUN apt-get -y install postgresql-client-17

RUN pip install poetry==1.6.1
RUN poetry config virtualenvs.create false

COPY ./app/pyproject.toml ./app/poetry.lock* ./

RUN poetry install --no-interaction

COPY ./app ./

RUN chmod +x ./entrypoint.sh

RUN mkdir backups

CMD ["./entrypoint.sh"]

