version: "3"
services:
  timescaledb:
    image: timescale/timescaledb-postgis:2.1.0-pg12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  postgres_12:
    image: postgres:12.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  postgres_13:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  postgres_14:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  postgres_15:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  minio:
    image: minio/minio:RELEASE.2021-11-24T23-19-33Z
    command: server /data
    ports:
      - "9000:9000"

  timescaledb-backup:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./app:/app"
      - "./app/backups:/app/backups"
