version: "3"
services:
  timescaledb:
    image: timescale/timescaledb-postgis:2.1.0-pg12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"

  timescaledb-backup:
    #image: askblaker/timescaledb-backup
    image: tb:latest
    volumes:
      - timescaledb-backup:/app/backups
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_UPLOAD: "true"
      MODE: daily_21_35

  timescaledb-restore:
    #image: askblaker/timescaledb-backup
    image: tb:latest
    volumes:
      - timescaledb-backup:/app/backups
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      RESTORE_OVERWRITE: "true"
      MODE: restore_latest_s3_file
      
volumes:
  timescaledb-backup: