name: build-test-push-to-docker-hub
on:
  release:
    types: [published]
    branches:
      - 'main'
    tags:
      - 'v*'
jobs:
  build-test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build image
      run: docker-compose build timescaledb-backup
    - name: Lint with flake8
      run: docker-compose run --rm timescaledb-backup poetry run flake8 .
    - name: Run black
      run: docker-compose run --rm timescaledb-backup poetry run black .
    - name: Run isort
      run: docker-compose run --rm timescaledb-backup poetry run isort .
    - name: Start containers
      run: docker-compose -f ./docker-compose.yml up -d timescaledb postgres_12 postgres_13 minio
    - name: Check running containers
      run: docker ps -a
    - name: Run test
      run: docker-compose -f ./docker-compose.yml run --rm timescaledb-backup poetry run pytest --cov=app ./tests/ 

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-test-coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            askblaker/timescaledb-backup
          tags: |
            type=semver,pattern={{version}}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}